package br.com.dsg.appteste.views;

import javax.swing.JLabel;

import br.com.dsg.swing.tela.layout.AbsoluteConstraints;
import br.com.dsg.swing.tela.layout.AbsoluteLayout;
import br.com.dsg.swing.util.Constantes;

/**
 *
 * @author dgiroto
 */
public class ConfigView extends javax.swing.JPanel {

    /**
     * Creates new form ConfigView
     */
    public ConfigView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        btGravar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        abas = new javax.swing.JTabbedPane();
        abaTela = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomeSistema = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        siglaSistema = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        alturaSistema = new javax.swing.JTextField();
        larguraSistema = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        larguraMenuAberto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        larguraAppBar = new javax.swing.JTextField();
        larguraMenuFechado = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inicMenuAberto = new javax.swing.JCheckBox();
        appSemBordaSistema = new javax.swing.JCheckBox();
        abaOutros = new javax.swing.JPanel();

        setBackground(java.awt.Color.white);
        setLayout(new java.awt.BorderLayout());

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(java.awt.Color.white);
        jToolBar1.setBorder(null);
        jToolBar1.setFloatable(false);
        jToolBar1.setForeground(java.awt.Color.white);
        jToolBar1.setRollover(true);

        btGravar.setText("Gravar");
        btGravar.setFocusable(false);
        btGravar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btGravar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btGravar);

        btCancelar.setText("Cancelar");
        btCancelar.setFocusable(false);
        btCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btCancelar);

        jPanel4.add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        add(jPanel4, java.awt.BorderLayout.PAGE_END);

        abas.setBackground(java.awt.Color.white);
        abas.setBorder(null);
        abas.setForeground(java.awt.Color.white);

        abaTela.setBackground(java.awt.Color.white);
        abaTela.setBorder(null);
        abaTela.setForeground(java.awt.Color.white);

        jLabel1.setText("Nome Sistema");

        jLabel2.setText("Sigla");

        jLabel3.setText("Altura X Largura");

        jLabel5.setText("Largura menu (aberto X fechado)");

        jLabel6.setText("Largura Barra do aplicativo");

        jLabel4.setText("X");

        jLabel7.setText("X");

        inicMenuAberto.setSelected(true);
        inicMenuAberto.setText("Menu Inicializa Aberto");

        appSemBordaSistema.setSelected(true);
        appSemBordaSistema.setText("Desetiva borda do sistema");

        javax.swing.GroupLayout abaTelaLayout = new javax.swing.GroupLayout(abaTela);
        abaTela.setLayout(abaTelaLayout);
        abaTelaLayout.setHorizontalGroup(
            abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaTelaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addGroup(abaTelaLayout.createSequentialGroup()
                        .addComponent(alturaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(larguraSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addComponent(larguraAppBar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(abaTelaLayout.createSequentialGroup()
                        .addComponent(larguraMenuAberto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(larguraMenuFechado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(nomeSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(siglaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(inicMenuAberto)
                    .addComponent(appSemBordaSistema))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        abaTelaLayout.setVerticalGroup(
            abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(abaTelaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siglaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(alturaSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(larguraSistema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(larguraMenuAberto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(larguraMenuFechado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(inicMenuAberto))
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(abaTelaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(larguraAppBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(appSemBordaSistema))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        abas.addTab("Aplicativo", null, abaTela, "");

        abaOutros.setBackground(java.awt.Color.white);

        javax.swing.GroupLayout abaOutrosLayout = new javax.swing.GroupLayout(abaOutros);
        abaOutros.setLayout(abaOutrosLayout);
        abaOutrosLayout.setHorizontalGroup(
            abaOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
        );
        abaOutrosLayout.setVerticalGroup(
            abaOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 282, Short.MAX_VALUE)
        );

        abas.addTab("Outras Configurações", abaOutros);

        add(abas, java.awt.BorderLayout.CENTER);
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JPanel abaOutros;
    private javax.swing.JPanel abaTela;
    private javax.swing.JTabbedPane abas;
    private javax.swing.JTextField alturaSistema;
    private javax.swing.JCheckBox appSemBordaSistema;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGravar;
    private javax.swing.JCheckBox inicMenuAberto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField larguraAppBar;
    private javax.swing.JTextField larguraMenuAberto;
    private javax.swing.JTextField larguraMenuFechado;
    private javax.swing.JTextField larguraSistema;
    private javax.swing.JTextField nomeSistema;
    private javax.swing.JTextField siglaSistema;
    // End of variables declaration         
	public javax.swing.JTabbedPane getAbas() {
		return abas;
	}

	public javax.swing.JTextField getAlturaSistema() {
		return alturaSistema;
	}

	public javax.swing.JButton getBtCancelar() {
		return btCancelar;
	}

	public javax.swing.JButton getBtGravar() {
		return btGravar;
	}

	public javax.swing.JCheckBox getInicMenuAberto() {
		return inicMenuAberto;
	}

	public javax.swing.JTextField getLarguraAppBar() {
		return larguraAppBar;
	}

	public javax.swing.JTextField getLarguraMenuAberto() {
		return larguraMenuAberto;
	}

	public javax.swing.JTextField getLarguraMenuFechado() {
		return larguraMenuFechado;
	}

	public javax.swing.JTextField getLarguraSistema() {
		return larguraSistema;
	}

	public javax.swing.JTextField getNomeSistema() {
		return nomeSistema;
	}

	public javax.swing.JTextField getSiglaSistema() {
		return siglaSistema;
	}
    
    
}